// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: reaction.proto

package cpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Reaction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Emoji              *string `protobuf:"bytes,3,opt,name=emoji,proto3,oneof" json:"emoji,omitempty"`
	TextRepresentation *string `protobuf:"bytes,4,opt,name=text_representation,json=textRepresentation,proto3,oneof" json:"text_representation,omitempty"`
}

func (x *Reaction) Reset() {
	*x = Reaction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reaction_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reaction) ProtoMessage() {}

func (x *Reaction) ProtoReflect() protoreflect.Message {
	mi := &file_reaction_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reaction.ProtoReflect.Descriptor instead.
func (*Reaction) Descriptor() ([]byte, []int) {
	return file_reaction_proto_rawDescGZIP(), []int{0}
}

func (x *Reaction) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Reaction) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Reaction) GetEmoji() string {
	if x != nil && x.Emoji != nil {
		return *x.Emoji
	}
	return ""
}

func (x *Reaction) GetTextRepresentation() string {
	if x != nil && x.TextRepresentation != nil {
		return *x.TextRepresentation
	}
	return ""
}

type ReactionAggregated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 int64   `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Count              int64   `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Name               string  `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Emoji              *string `protobuf:"bytes,4,opt,name=emoji,proto3,oneof" json:"emoji,omitempty"`
	TextRepresentation *string `protobuf:"bytes,5,opt,name=text_representation,json=textRepresentation,proto3,oneof" json:"text_representation,omitempty"`
}

func (x *ReactionAggregated) Reset() {
	*x = ReactionAggregated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_reaction_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReactionAggregated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReactionAggregated) ProtoMessage() {}

func (x *ReactionAggregated) ProtoReflect() protoreflect.Message {
	mi := &file_reaction_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReactionAggregated.ProtoReflect.Descriptor instead.
func (*ReactionAggregated) Descriptor() ([]byte, []int) {
	return file_reaction_proto_rawDescGZIP(), []int{1}
}

func (x *ReactionAggregated) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ReactionAggregated) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *ReactionAggregated) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReactionAggregated) GetEmoji() string {
	if x != nil && x.Emoji != nil {
		return *x.Emoji
	}
	return ""
}

func (x *ReactionAggregated) GetTextRepresentation() string {
	if x != nil && x.TextRepresentation != nil {
		return *x.TextRepresentation
	}
	return ""
}

var File_reaction_proto protoreflect.FileDescriptor

var file_reaction_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x72, 0x65, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x63, 0x70, 0x62, 0x22, 0xa1, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x88, 0x01,
	0x01, 0x12, 0x34, 0x0a, 0x13, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x72, 0x65, 0x70, 0x72, 0x65, 0x73,
	0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01,
	0x52, 0x12, 0x74, 0x65, 0x78, 0x74, 0x52, 0x65, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f, 0x65, 0x6d, 0x6f, 0x6a,
	0x69, 0x42, 0x16, 0x0a, 0x14, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x72, 0x65, 0x70, 0x72, 0x65,
	0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xc1, 0x01, 0x0a, 0x12, 0x52, 0x65,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x41, 0x67, 0x67, 0x72, 0x65, 0x67, 0x61, 0x74, 0x65, 0x64,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x05, 0x65, 0x6d,
	0x6f, 0x6a, 0x69, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x05, 0x65, 0x6d, 0x6f,
	0x6a, 0x69, 0x88, 0x01, 0x01, 0x12, 0x34, 0x0a, 0x13, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x72, 0x65,
	0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x01, 0x52, 0x12, 0x74, 0x65, 0x78, 0x74, 0x52, 0x65, 0x70, 0x72, 0x65, 0x73,
	0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x42, 0x08, 0x0a, 0x06, 0x5f,
	0x65, 0x6d, 0x6f, 0x6a, 0x69, 0x42, 0x16, 0x0a, 0x14, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x5f, 0x72,
	0x65, 0x70, 0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x2d, 0x5a,
	0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x76, 0x61, 0x73,
	0x68, 0x2f, 0x62, 0x67, 0x6d, 0x6f, 0x6f, 0x64, 0x2d, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x73,
	0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_reaction_proto_rawDescOnce sync.Once
	file_reaction_proto_rawDescData = file_reaction_proto_rawDesc
)

func file_reaction_proto_rawDescGZIP() []byte {
	file_reaction_proto_rawDescOnce.Do(func() {
		file_reaction_proto_rawDescData = protoimpl.X.CompressGZIP(file_reaction_proto_rawDescData)
	})
	return file_reaction_proto_rawDescData
}

var file_reaction_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_reaction_proto_goTypes = []interface{}{
	(*Reaction)(nil),           // 0: cpb.Reaction
	(*ReactionAggregated)(nil), // 1: cpb.ReactionAggregated
}
var file_reaction_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_reaction_proto_init() }
func file_reaction_proto_init() {
	if File_reaction_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_reaction_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reaction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_reaction_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReactionAggregated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_reaction_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_reaction_proto_msgTypes[1].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_reaction_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_reaction_proto_goTypes,
		DependencyIndexes: file_reaction_proto_depIdxs,
		MessageInfos:      file_reaction_proto_msgTypes,
	}.Build()
	File_reaction_proto = out.File
	file_reaction_proto_rawDesc = nil
	file_reaction_proto_goTypes = nil
	file_reaction_proto_depIdxs = nil
}
