// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: rpc_get_circles.proto

package cpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetJoinedCirclesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *GetJoinedCirclesRequest) Reset() {
	*x = GetJoinedCirclesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_get_circles_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJoinedCirclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJoinedCirclesRequest) ProtoMessage() {}

func (x *GetJoinedCirclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_circles_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJoinedCirclesRequest.ProtoReflect.Descriptor instead.
func (*GetJoinedCirclesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_circles_proto_rawDescGZIP(), []int{0}
}

func (x *GetJoinedCirclesRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetJoinedCirclesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Circles []*Circle `protobuf:"bytes,1,rep,name=circles,proto3" json:"circles,omitempty"`
}

func (x *GetJoinedCirclesResponse) Reset() {
	*x = GetJoinedCirclesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_get_circles_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetJoinedCirclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetJoinedCirclesResponse) ProtoMessage() {}

func (x *GetJoinedCirclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_circles_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetJoinedCirclesResponse.ProtoReflect.Descriptor instead.
func (*GetJoinedCirclesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_circles_proto_rawDescGZIP(), []int{1}
}

func (x *GetJoinedCirclesResponse) GetCircles() []*Circle {
	if x != nil {
		return x.Circles
	}
	return nil
}

type GetRequestedCirclesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page int64 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *GetRequestedCirclesRequest) Reset() {
	*x = GetRequestedCirclesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_get_circles_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequestedCirclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestedCirclesRequest) ProtoMessage() {}

func (x *GetRequestedCirclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_circles_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestedCirclesRequest.ProtoReflect.Descriptor instead.
func (*GetRequestedCirclesRequest) Descriptor() ([]byte, []int) {
	return file_rpc_get_circles_proto_rawDescGZIP(), []int{2}
}

func (x *GetRequestedCirclesRequest) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetRequestedCirclesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Circles []*Circle `protobuf:"bytes,1,rep,name=circles,proto3" json:"circles,omitempty"`
}

func (x *GetRequestedCirclesResponse) Reset() {
	*x = GetRequestedCirclesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_get_circles_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRequestedCirclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequestedCirclesResponse) ProtoMessage() {}

func (x *GetRequestedCirclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_get_circles_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequestedCirclesResponse.ProtoReflect.Descriptor instead.
func (*GetRequestedCirclesResponse) Descriptor() ([]byte, []int) {
	return file_rpc_get_circles_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequestedCirclesResponse) GetCircles() []*Circle {
	if x != nil {
		return x.Circles
	}
	return nil
}

var File_rpc_get_circles_proto protoreflect.FileDescriptor

var file_rpc_get_circles_proto_rawDesc = []byte{
	0x0a, 0x15, 0x72, 0x70, 0x63, 0x5f, 0x67, 0x65, 0x74, 0x5f, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x63, 0x70, 0x62, 0x1a, 0x0c, 0x63, 0x69,
	0x72, 0x63, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x2d, 0x0a, 0x17, 0x47, 0x65,
	0x74, 0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x41, 0x0a, 0x18, 0x47, 0x65, 0x74,
	0x4a, 0x6f, 0x69, 0x6e, 0x65, 0x64, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x07, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x63, 0x70, 0x62, 0x2e, 0x43, 0x69, 0x72,
	0x63, 0x6c, 0x65, 0x52, 0x07, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x73, 0x22, 0x30, 0x0a, 0x1a,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x43, 0x69, 0x72, 0x63,
	0x6c, 0x65, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22, 0x44,
	0x0a, 0x1b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x65, 0x64, 0x43, 0x69,
	0x72, 0x63, 0x6c, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a,
	0x07, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x63, 0x70, 0x62, 0x2e, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x52, 0x07, 0x63, 0x69, 0x72,
	0x63, 0x6c, 0x65, 0x73, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x7a, 0x76, 0x61, 0x73, 0x68, 0x2f, 0x62, 0x67, 0x6d, 0x6f, 0x6f, 0x64, 0x2d,
	0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x63, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_get_circles_proto_rawDescOnce sync.Once
	file_rpc_get_circles_proto_rawDescData = file_rpc_get_circles_proto_rawDesc
)

func file_rpc_get_circles_proto_rawDescGZIP() []byte {
	file_rpc_get_circles_proto_rawDescOnce.Do(func() {
		file_rpc_get_circles_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_get_circles_proto_rawDescData)
	})
	return file_rpc_get_circles_proto_rawDescData
}

var file_rpc_get_circles_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_get_circles_proto_goTypes = []interface{}{
	(*GetJoinedCirclesRequest)(nil),     // 0: cpb.GetJoinedCirclesRequest
	(*GetJoinedCirclesResponse)(nil),    // 1: cpb.GetJoinedCirclesResponse
	(*GetRequestedCirclesRequest)(nil),  // 2: cpb.GetRequestedCirclesRequest
	(*GetRequestedCirclesResponse)(nil), // 3: cpb.GetRequestedCirclesResponse
	(*Circle)(nil),                      // 4: cpb.Circle
}
var file_rpc_get_circles_proto_depIdxs = []int32{
	4, // 0: cpb.GetJoinedCirclesResponse.circles:type_name -> cpb.Circle
	4, // 1: cpb.GetRequestedCirclesResponse.circles:type_name -> cpb.Circle
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_get_circles_proto_init() }
func file_rpc_get_circles_proto_init() {
	if File_rpc_get_circles_proto != nil {
		return
	}
	file_circle_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_get_circles_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJoinedCirclesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_get_circles_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetJoinedCirclesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_get_circles_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequestedCirclesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_get_circles_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRequestedCirclesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_get_circles_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_get_circles_proto_goTypes,
		DependencyIndexes: file_rpc_get_circles_proto_depIdxs,
		MessageInfos:      file_rpc_get_circles_proto_msgTypes,
	}.Build()
	File_rpc_get_circles_proto = out.File
	file_rpc_get_circles_proto_rawDesc = nil
	file_rpc_get_circles_proto_goTypes = nil
	file_rpc_get_circles_proto_depIdxs = nil
}
