// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: rpc_circle_wp_change_access.proto

package cpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AccessType int32

const (
	AccessType_ACCEPT_ALL AccessType = 0
	AccessType_ASK_FIRST  AccessType = 1
	AccessType_REJECT_ALL AccessType = 2
)

// Enum value maps for AccessType.
var (
	AccessType_name = map[int32]string{
		0: "ACCEPT_ALL",
		1: "ASK_FIRST",
		2: "REJECT_ALL",
	}
	AccessType_value = map[string]int32{
		"ACCEPT_ALL": 0,
		"ASK_FIRST":  1,
		"REJECT_ALL": 2,
	}
)

func (x AccessType) Enum() *AccessType {
	p := new(AccessType)
	*p = x
	return p
}

func (x AccessType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessType) Descriptor() protoreflect.EnumDescriptor {
	return file_rpc_circle_wp_change_access_proto_enumTypes[0].Descriptor()
}

func (AccessType) Type() protoreflect.EnumType {
	return &file_rpc_circle_wp_change_access_proto_enumTypes[0]
}

func (x AccessType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessType.Descriptor instead.
func (AccessType) EnumDescriptor() ([]byte, []int) {
	return file_rpc_circle_wp_change_access_proto_rawDescGZIP(), []int{0}
}

type GetCircleWPChangeAccessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CircleId string `protobuf:"bytes,1,opt,name=circle_id,json=circleId,proto3" json:"circle_id,omitempty"`
}

func (x *GetCircleWPChangeAccessRequest) Reset() {
	*x = GetCircleWPChangeAccessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_circle_wp_change_access_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCircleWPChangeAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCircleWPChangeAccessRequest) ProtoMessage() {}

func (x *GetCircleWPChangeAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_circle_wp_change_access_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCircleWPChangeAccessRequest.ProtoReflect.Descriptor instead.
func (*GetCircleWPChangeAccessRequest) Descriptor() ([]byte, []int) {
	return file_rpc_circle_wp_change_access_proto_rawDescGZIP(), []int{0}
}

func (x *GetCircleWPChangeAccessRequest) GetCircleId() string {
	if x != nil {
		return x.CircleId
	}
	return ""
}

type SetCircleWPChangeAccessRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CircleId   string     `protobuf:"bytes,1,opt,name=circle_id,json=circleId,proto3" json:"circle_id,omitempty"`
	AccessType AccessType `protobuf:"varint,2,opt,name=access_type,json=accessType,proto3,enum=cpb.AccessType" json:"access_type,omitempty"`
}

func (x *SetCircleWPChangeAccessRequest) Reset() {
	*x = SetCircleWPChangeAccessRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_circle_wp_change_access_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetCircleWPChangeAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetCircleWPChangeAccessRequest) ProtoMessage() {}

func (x *SetCircleWPChangeAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_circle_wp_change_access_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetCircleWPChangeAccessRequest.ProtoReflect.Descriptor instead.
func (*SetCircleWPChangeAccessRequest) Descriptor() ([]byte, []int) {
	return file_rpc_circle_wp_change_access_proto_rawDescGZIP(), []int{1}
}

func (x *SetCircleWPChangeAccessRequest) GetCircleId() string {
	if x != nil {
		return x.CircleId
	}
	return ""
}

func (x *SetCircleWPChangeAccessRequest) GetAccessType() AccessType {
	if x != nil {
		return x.AccessType
	}
	return AccessType_ACCEPT_ALL
}

type CircleWPChangeAccessResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CircleId   string     `protobuf:"bytes,1,opt,name=circle_id,json=circleId,proto3" json:"circle_id,omitempty"`
	AccessType AccessType `protobuf:"varint,2,opt,name=access_type,json=accessType,proto3,enum=cpb.AccessType" json:"access_type,omitempty"`
}

func (x *CircleWPChangeAccessResponse) Reset() {
	*x = CircleWPChangeAccessResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_circle_wp_change_access_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CircleWPChangeAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CircleWPChangeAccessResponse) ProtoMessage() {}

func (x *CircleWPChangeAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_circle_wp_change_access_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CircleWPChangeAccessResponse.ProtoReflect.Descriptor instead.
func (*CircleWPChangeAccessResponse) Descriptor() ([]byte, []int) {
	return file_rpc_circle_wp_change_access_proto_rawDescGZIP(), []int{2}
}

func (x *CircleWPChangeAccessResponse) GetCircleId() string {
	if x != nil {
		return x.CircleId
	}
	return ""
}

func (x *CircleWPChangeAccessResponse) GetAccessType() AccessType {
	if x != nil {
		return x.AccessType
	}
	return AccessType_ACCEPT_ALL
}

var File_rpc_circle_wp_change_access_proto protoreflect.FileDescriptor

var file_rpc_circle_wp_change_access_proto_rawDesc = []byte{
	0x0a, 0x21, 0x72, 0x70, 0x63, 0x5f, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x5f, 0x77, 0x70, 0x5f,
	0x63, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x03, 0x63, 0x70, 0x62, 0x22, 0x3d, 0x0a, 0x1e, 0x47, 0x65, 0x74, 0x43,
	0x69, 0x72, 0x63, 0x6c, 0x65, 0x57, 0x50, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x69,
	0x72, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63,
	0x69, 0x72, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x6f, 0x0a, 0x1e, 0x53, 0x65, 0x74, 0x43, 0x69,
	0x72, 0x63, 0x6c, 0x65, 0x57, 0x50, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x69, 0x72,
	0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x69,
	0x72, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x63, 0x70,
	0x62, 0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x22, 0x6d, 0x0a, 0x1c, 0x43, 0x69, 0x72, 0x63,
	0x6c, 0x65, 0x57, 0x50, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x69, 0x72, 0x63,
	0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x69, 0x72,
	0x63, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x30, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f,
	0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x63, 0x70, 0x62,
	0x2e, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0a, 0x61, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x54, 0x79, 0x70, 0x65, 0x2a, 0x3b, 0x0a, 0x0a, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x43, 0x43, 0x45, 0x50, 0x54, 0x5f,
	0x41, 0x4c, 0x4c, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x53, 0x4b, 0x5f, 0x46, 0x49, 0x52,
	0x53, 0x54, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x45, 0x4a, 0x45, 0x43, 0x54, 0x5f, 0x41,
	0x4c, 0x4c, 0x10, 0x02, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63,
	0x6f, 0x6d, 0x2f, 0x7a, 0x76, 0x61, 0x73, 0x68, 0x2f, 0x62, 0x67, 0x6d, 0x6f, 0x6f, 0x64, 0x2d,
	0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x63, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_circle_wp_change_access_proto_rawDescOnce sync.Once
	file_rpc_circle_wp_change_access_proto_rawDescData = file_rpc_circle_wp_change_access_proto_rawDesc
)

func file_rpc_circle_wp_change_access_proto_rawDescGZIP() []byte {
	file_rpc_circle_wp_change_access_proto_rawDescOnce.Do(func() {
		file_rpc_circle_wp_change_access_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_circle_wp_change_access_proto_rawDescData)
	})
	return file_rpc_circle_wp_change_access_proto_rawDescData
}

var file_rpc_circle_wp_change_access_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rpc_circle_wp_change_access_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_circle_wp_change_access_proto_goTypes = []interface{}{
	(AccessType)(0),                        // 0: cpb.AccessType
	(*GetCircleWPChangeAccessRequest)(nil), // 1: cpb.GetCircleWPChangeAccessRequest
	(*SetCircleWPChangeAccessRequest)(nil), // 2: cpb.SetCircleWPChangeAccessRequest
	(*CircleWPChangeAccessResponse)(nil),   // 3: cpb.CircleWPChangeAccessResponse
}
var file_rpc_circle_wp_change_access_proto_depIdxs = []int32{
	0, // 0: cpb.SetCircleWPChangeAccessRequest.access_type:type_name -> cpb.AccessType
	0, // 1: cpb.CircleWPChangeAccessResponse.access_type:type_name -> cpb.AccessType
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_circle_wp_change_access_proto_init() }
func file_rpc_circle_wp_change_access_proto_init() {
	if File_rpc_circle_wp_change_access_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_circle_wp_change_access_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCircleWPChangeAccessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_circle_wp_change_access_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetCircleWPChangeAccessRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_circle_wp_change_access_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CircleWPChangeAccessResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_circle_wp_change_access_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_circle_wp_change_access_proto_goTypes,
		DependencyIndexes: file_rpc_circle_wp_change_access_proto_depIdxs,
		EnumInfos:         file_rpc_circle_wp_change_access_proto_enumTypes,
		MessageInfos:      file_rpc_circle_wp_change_access_proto_msgTypes,
	}.Build()
	File_rpc_circle_wp_change_access_proto = out.File
	file_rpc_circle_wp_change_access_proto_rawDesc = nil
	file_rpc_circle_wp_change_access_proto_goTypes = nil
	file_rpc_circle_wp_change_access_proto_depIdxs = nil
}
