// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: rpc_view_circle.proto

package cpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ViewCircleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CircleId string `protobuf:"bytes,1,opt,name=circle_id,json=circleId,proto3" json:"circle_id,omitempty"`
}

func (x *ViewCircleRequest) Reset() {
	*x = ViewCircleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_view_circle_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewCircleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewCircleRequest) ProtoMessage() {}

func (x *ViewCircleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_view_circle_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewCircleRequest.ProtoReflect.Descriptor instead.
func (*ViewCircleRequest) Descriptor() ([]byte, []int) {
	return file_rpc_view_circle_proto_rawDescGZIP(), []int{0}
}

func (x *ViewCircleRequest) GetCircleId() string {
	if x != nil {
		return x.CircleId
	}
	return ""
}

type ViewCircleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Circle *CircleMeta `protobuf:"bytes,1,opt,name=circle,proto3" json:"circle,omitempty"`
}

func (x *ViewCircleResponse) Reset() {
	*x = ViewCircleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_view_circle_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ViewCircleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ViewCircleResponse) ProtoMessage() {}

func (x *ViewCircleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_view_circle_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ViewCircleResponse.ProtoReflect.Descriptor instead.
func (*ViewCircleResponse) Descriptor() ([]byte, []int) {
	return file_rpc_view_circle_proto_rawDescGZIP(), []int{1}
}

func (x *ViewCircleResponse) GetCircle() *CircleMeta {
	if x != nil {
		return x.Circle
	}
	return nil
}

var File_rpc_view_circle_proto protoreflect.FileDescriptor

var file_rpc_view_circle_proto_rawDesc = []byte{
	0x0a, 0x15, 0x72, 0x70, 0x63, 0x5f, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x63, 0x69, 0x72, 0x63, 0x6c,
	0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x63, 0x70, 0x62, 0x1a, 0x0c, 0x63, 0x69,
	0x72, 0x63, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x30, 0x0a, 0x11, 0x56, 0x69,
	0x65, 0x77, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x12,
	0x56, 0x69, 0x65, 0x77, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x63, 0x70, 0x62, 0x2e, 0x43, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x4d,
	0x65, 0x74, 0x61, 0x52, 0x06, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x42, 0x2d, 0x5a, 0x2b, 0x67,
	0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x76, 0x61, 0x73, 0x68, 0x2f,
	0x62, 0x67, 0x6d, 0x6f, 0x6f, 0x64, 0x2d, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x73, 0x2d, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f, 0x63, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_rpc_view_circle_proto_rawDescOnce sync.Once
	file_rpc_view_circle_proto_rawDescData = file_rpc_view_circle_proto_rawDesc
)

func file_rpc_view_circle_proto_rawDescGZIP() []byte {
	file_rpc_view_circle_proto_rawDescOnce.Do(func() {
		file_rpc_view_circle_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_view_circle_proto_rawDescData)
	})
	return file_rpc_view_circle_proto_rawDescData
}

var file_rpc_view_circle_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_rpc_view_circle_proto_goTypes = []interface{}{
	(*ViewCircleRequest)(nil),  // 0: cpb.ViewCircleRequest
	(*ViewCircleResponse)(nil), // 1: cpb.ViewCircleResponse
	(*CircleMeta)(nil),         // 2: cpb.CircleMeta
}
var file_rpc_view_circle_proto_depIdxs = []int32{
	2, // 0: cpb.ViewCircleResponse.circle:type_name -> cpb.CircleMeta
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_rpc_view_circle_proto_init() }
func file_rpc_view_circle_proto_init() {
	if File_rpc_view_circle_proto != nil {
		return
	}
	file_circle_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_view_circle_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewCircleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_view_circle_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ViewCircleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_view_circle_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_view_circle_proto_goTypes,
		DependencyIndexes: file_rpc_view_circle_proto_depIdxs,
		MessageInfos:      file_rpc_view_circle_proto_msgTypes,
	}.Build()
	File_rpc_view_circle_proto = out.File
	file_rpc_view_circle_proto_rawDesc = nil
	file_rpc_view_circle_proto_goTypes = nil
	file_rpc_view_circle_proto_depIdxs = nil
}
