// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: rpc_modify_circle_access.proto

package cpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PromoteToPosterRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CircleId string `protobuf:"bytes,1,opt,name=circle_id,json=circleId,proto3" json:"circle_id,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *PromoteToPosterRequest) Reset() {
	*x = PromoteToPosterRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_modify_circle_access_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PromoteToPosterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteToPosterRequest) ProtoMessage() {}

func (x *PromoteToPosterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_modify_circle_access_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteToPosterRequest.ProtoReflect.Descriptor instead.
func (*PromoteToPosterRequest) Descriptor() ([]byte, []int) {
	return file_rpc_modify_circle_access_proto_rawDescGZIP(), []int{0}
}

func (x *PromoteToPosterRequest) GetCircleId() string {
	if x != nil {
		return x.CircleId
	}
	return ""
}

func (x *PromoteToPosterRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type PromoteToAdminRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CircleId string `protobuf:"bytes,1,opt,name=circle_id,json=circleId,proto3" json:"circle_id,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *PromoteToAdminRequest) Reset() {
	*x = PromoteToAdminRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_modify_circle_access_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PromoteToAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PromoteToAdminRequest) ProtoMessage() {}

func (x *PromoteToAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_modify_circle_access_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PromoteToAdminRequest.ProtoReflect.Descriptor instead.
func (*PromoteToAdminRequest) Descriptor() ([]byte, []int) {
	return file_rpc_modify_circle_access_proto_rawDescGZIP(), []int{1}
}

func (x *PromoteToAdminRequest) GetCircleId() string {
	if x != nil {
		return x.CircleId
	}
	return ""
}

func (x *PromoteToAdminRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type DemoteToViewerRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CircleId string `protobuf:"bytes,1,opt,name=circle_id,json=circleId,proto3" json:"circle_id,omitempty"`
	UserId   string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
}

func (x *DemoteToViewerRequest) Reset() {
	*x = DemoteToViewerRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_modify_circle_access_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DemoteToViewerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DemoteToViewerRequest) ProtoMessage() {}

func (x *DemoteToViewerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_modify_circle_access_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DemoteToViewerRequest.ProtoReflect.Descriptor instead.
func (*DemoteToViewerRequest) Descriptor() ([]byte, []int) {
	return file_rpc_modify_circle_access_proto_rawDescGZIP(), []int{2}
}

func (x *DemoteToViewerRequest) GetCircleId() string {
	if x != nil {
		return x.CircleId
	}
	return ""
}

func (x *DemoteToViewerRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type AccessModificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CircleId      string `protobuf:"bytes,1,opt,name=circle_id,json=circleId,proto3" json:"circle_id,omitempty"`
	CurrentAccess string `protobuf:"bytes,2,opt,name=current_access,json=currentAccess,proto3" json:"current_access,omitempty"`
}

func (x *AccessModificationResponse) Reset() {
	*x = AccessModificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_modify_circle_access_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AccessModificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessModificationResponse) ProtoMessage() {}

func (x *AccessModificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_modify_circle_access_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessModificationResponse.ProtoReflect.Descriptor instead.
func (*AccessModificationResponse) Descriptor() ([]byte, []int) {
	return file_rpc_modify_circle_access_proto_rawDescGZIP(), []int{3}
}

func (x *AccessModificationResponse) GetCircleId() string {
	if x != nil {
		return x.CircleId
	}
	return ""
}

func (x *AccessModificationResponse) GetCurrentAccess() string {
	if x != nil {
		return x.CurrentAccess
	}
	return ""
}

var File_rpc_modify_circle_access_proto protoreflect.FileDescriptor

var file_rpc_modify_circle_access_proto_rawDesc = []byte{
	0x0a, 0x1e, 0x72, 0x70, 0x63, 0x5f, 0x6d, 0x6f, 0x64, 0x69, 0x66, 0x79, 0x5f, 0x63, 0x69, 0x72,
	0x63, 0x6c, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x63, 0x70, 0x62, 0x22, 0x4e, 0x0a, 0x16, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x65,
	0x54, 0x6f, 0x50, 0x6f, 0x73, 0x74, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x15, 0x50, 0x72, 0x6f, 0x6d, 0x6f, 0x74, 0x65,
	0x54, 0x6f, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x22, 0x4d, 0x0a, 0x15, 0x44, 0x65, 0x6d, 0x6f, 0x74, 0x65, 0x54, 0x6f,
	0x56, 0x69, 0x65, 0x77, 0x65, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x60, 0x0a, 0x1a, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x4d, 0x6f, 0x64,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x25,
	0x0a, 0x0e, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x63, 0x75, 0x72, 0x72, 0x65, 0x6e, 0x74, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x76, 0x61, 0x73, 0x68, 0x2f, 0x62, 0x67, 0x6d, 0x6f, 0x6f, 0x64,
	0x2d, 0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x73, 0x2d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x2f, 0x63, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_modify_circle_access_proto_rawDescOnce sync.Once
	file_rpc_modify_circle_access_proto_rawDescData = file_rpc_modify_circle_access_proto_rawDesc
)

func file_rpc_modify_circle_access_proto_rawDescGZIP() []byte {
	file_rpc_modify_circle_access_proto_rawDescOnce.Do(func() {
		file_rpc_modify_circle_access_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_modify_circle_access_proto_rawDescData)
	})
	return file_rpc_modify_circle_access_proto_rawDescData
}

var file_rpc_modify_circle_access_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_rpc_modify_circle_access_proto_goTypes = []interface{}{
	(*PromoteToPosterRequest)(nil),     // 0: cpb.PromoteToPosterRequest
	(*PromoteToAdminRequest)(nil),      // 1: cpb.PromoteToAdminRequest
	(*DemoteToViewerRequest)(nil),      // 2: cpb.DemoteToViewerRequest
	(*AccessModificationResponse)(nil), // 3: cpb.AccessModificationResponse
}
var file_rpc_modify_circle_access_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_rpc_modify_circle_access_proto_init() }
func file_rpc_modify_circle_access_proto_init() {
	if File_rpc_modify_circle_access_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_rpc_modify_circle_access_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PromoteToPosterRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_modify_circle_access_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PromoteToAdminRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_modify_circle_access_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DemoteToViewerRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_modify_circle_access_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AccessModificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_modify_circle_access_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_modify_circle_access_proto_goTypes,
		DependencyIndexes: file_rpc_modify_circle_access_proto_depIdxs,
		MessageInfos:      file_rpc_modify_circle_access_proto_msgTypes,
	}.Build()
	File_rpc_modify_circle_access_proto = out.File
	file_rpc_modify_circle_access_proto_rawDesc = nil
	file_rpc_modify_circle_access_proto_goTypes = nil
	file_rpc_modify_circle_access_proto_depIdxs = nil
}
