// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.23.4
// source: rpc_api_share_mood.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MoodInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CircleId      string  `protobuf:"bytes,1,opt,name=circle_id,json=circleId,proto3" json:"circle_id,omitempty"`
	SetBackground bool    `protobuf:"varint,2,opt,name=set_background,json=setBackground,proto3" json:"set_background,omitempty"`
	Description   *string `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ImageExt      string  `protobuf:"bytes,4,opt,name=image_ext,json=imageExt,proto3" json:"image_ext,omitempty"`
}

func (x *MoodInfo) Reset() {
	*x = MoodInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_api_share_mood_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MoodInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MoodInfo) ProtoMessage() {}

func (x *MoodInfo) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_api_share_mood_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MoodInfo.ProtoReflect.Descriptor instead.
func (*MoodInfo) Descriptor() ([]byte, []int) {
	return file_rpc_api_share_mood_proto_rawDescGZIP(), []int{0}
}

func (x *MoodInfo) GetCircleId() string {
	if x != nil {
		return x.CircleId
	}
	return ""
}

func (x *MoodInfo) GetSetBackground() bool {
	if x != nil {
		return x.SetBackground
	}
	return false
}

func (x *MoodInfo) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *MoodInfo) GetImageExt() string {
	if x != nil {
		return x.ImageExt
	}
	return ""
}

type ShareMoodRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Data:
	//
	//	*ShareMoodRequest_Info
	//	*ShareMoodRequest_ChunkData
	Data isShareMoodRequest_Data `protobuf_oneof:"data"`
}

func (x *ShareMoodRequest) Reset() {
	*x = ShareMoodRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_api_share_mood_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareMoodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareMoodRequest) ProtoMessage() {}

func (x *ShareMoodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_api_share_mood_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareMoodRequest.ProtoReflect.Descriptor instead.
func (*ShareMoodRequest) Descriptor() ([]byte, []int) {
	return file_rpc_api_share_mood_proto_rawDescGZIP(), []int{1}
}

func (m *ShareMoodRequest) GetData() isShareMoodRequest_Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (x *ShareMoodRequest) GetInfo() *MoodInfo {
	if x, ok := x.GetData().(*ShareMoodRequest_Info); ok {
		return x.Info
	}
	return nil
}

func (x *ShareMoodRequest) GetChunkData() []byte {
	if x, ok := x.GetData().(*ShareMoodRequest_ChunkData); ok {
		return x.ChunkData
	}
	return nil
}

type isShareMoodRequest_Data interface {
	isShareMoodRequest_Data()
}

type ShareMoodRequest_Info struct {
	Info *MoodInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type ShareMoodRequest_ChunkData struct {
	ChunkData []byte `protobuf:"bytes,2,opt,name=chunk_data,json=chunkData,proto3,oneof"`
}

func (*ShareMoodRequest_Info) isShareMoodRequest_Data() {}

func (*ShareMoodRequest_ChunkData) isShareMoodRequest_Data() {}

type ShareMoodResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mood *Mood `protobuf:"bytes,1,opt,name=mood,proto3" json:"mood,omitempty"`
}

func (x *ShareMoodResponse) Reset() {
	*x = ShareMoodResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_rpc_api_share_mood_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ShareMoodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShareMoodResponse) ProtoMessage() {}

func (x *ShareMoodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rpc_api_share_mood_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShareMoodResponse.ProtoReflect.Descriptor instead.
func (*ShareMoodResponse) Descriptor() ([]byte, []int) {
	return file_rpc_api_share_mood_proto_rawDescGZIP(), []int{2}
}

func (x *ShareMoodResponse) GetMood() *Mood {
	if x != nil {
		return x.Mood
	}
	return nil
}

var File_rpc_api_share_mood_proto protoreflect.FileDescriptor

var file_rpc_api_share_mood_proto_rawDesc = []byte{
	0x0a, 0x18, 0x72, 0x70, 0x63, 0x5f, 0x61, 0x70, 0x69, 0x5f, 0x73, 0x68, 0x61, 0x72, 0x65, 0x5f,
	0x6d, 0x6f, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x1a, 0x0e,
	0x61, 0x70, 0x69, 0x5f, 0x6d, 0x6f, 0x6f, 0x64, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa2,
	0x01, 0x0a, 0x08, 0x4d, 0x6f, 0x6f, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1b, 0x0a, 0x09, 0x63,
	0x69, 0x72, 0x63, 0x6c, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x63, 0x69, 0x72, 0x63, 0x6c, 0x65, 0x49, 0x64, 0x12, 0x25, 0x0a, 0x0e, 0x73, 0x65, 0x74, 0x5f,
	0x62, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x0d, 0x73, 0x65, 0x74, 0x42, 0x61, 0x63, 0x6b, 0x67, 0x72, 0x6f, 0x75, 0x6e, 0x64, 0x12,
	0x25, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f,
	0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65,
	0x45, 0x78, 0x74, 0x42, 0x0e, 0x0a, 0x0c, 0x5f, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0x5f, 0x0a, 0x10, 0x53, 0x68, 0x61, 0x72, 0x65, 0x4d, 0x6f, 0x6f, 0x64,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x6f, 0x6f, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x48, 0x00, 0x52, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x12, 0x1f, 0x0a, 0x0a, 0x63,
	0x68, 0x75, 0x6e, 0x6b, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x48,
	0x00, 0x52, 0x09, 0x63, 0x68, 0x75, 0x6e, 0x6b, 0x44, 0x61, 0x74, 0x61, 0x42, 0x06, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x22, 0x31, 0x0a, 0x11, 0x53, 0x68, 0x61, 0x72, 0x65, 0x4d, 0x6f, 0x6f,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x04, 0x6d, 0x6f, 0x6f,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x70, 0x62, 0x2e, 0x4d, 0x6f, 0x6f,
	0x64, 0x52, 0x04, 0x6d, 0x6f, 0x6f, 0x64, 0x42, 0x28, 0x5a, 0x26, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x7a, 0x76, 0x61, 0x73, 0x68, 0x2f, 0x62, 0x67, 0x6d, 0x6f,
	0x6f, 0x64, 0x2d, 0x61, 0x70, 0x69, 0x2d, 0x67, 0x61, 0x74, 0x65, 0x77, 0x61, 0x79, 0x2f, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_rpc_api_share_mood_proto_rawDescOnce sync.Once
	file_rpc_api_share_mood_proto_rawDescData = file_rpc_api_share_mood_proto_rawDesc
)

func file_rpc_api_share_mood_proto_rawDescGZIP() []byte {
	file_rpc_api_share_mood_proto_rawDescOnce.Do(func() {
		file_rpc_api_share_mood_proto_rawDescData = protoimpl.X.CompressGZIP(file_rpc_api_share_mood_proto_rawDescData)
	})
	return file_rpc_api_share_mood_proto_rawDescData
}

var file_rpc_api_share_mood_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_rpc_api_share_mood_proto_goTypes = []interface{}{
	(*MoodInfo)(nil),          // 0: pb.MoodInfo
	(*ShareMoodRequest)(nil),  // 1: pb.ShareMoodRequest
	(*ShareMoodResponse)(nil), // 2: pb.ShareMoodResponse
	(*Mood)(nil),              // 3: pb.Mood
}
var file_rpc_api_share_mood_proto_depIdxs = []int32{
	0, // 0: pb.ShareMoodRequest.info:type_name -> pb.MoodInfo
	3, // 1: pb.ShareMoodResponse.mood:type_name -> pb.Mood
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rpc_api_share_mood_proto_init() }
func file_rpc_api_share_mood_proto_init() {
	if File_rpc_api_share_mood_proto != nil {
		return
	}
	file_api_mood_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_rpc_api_share_mood_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MoodInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_api_share_mood_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareMoodRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_rpc_api_share_mood_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ShareMoodResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_rpc_api_share_mood_proto_msgTypes[0].OneofWrappers = []interface{}{}
	file_rpc_api_share_mood_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ShareMoodRequest_Info)(nil),
		(*ShareMoodRequest_ChunkData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_rpc_api_share_mood_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_rpc_api_share_mood_proto_goTypes,
		DependencyIndexes: file_rpc_api_share_mood_proto_depIdxs,
		MessageInfos:      file_rpc_api_share_mood_proto_msgTypes,
	}.Build()
	File_rpc_api_share_mood_proto = out.File
	file_rpc_api_share_mood_proto_rawDesc = nil
	file_rpc_api_share_mood_proto_goTypes = nil
	file_rpc_api_share_mood_proto_depIdxs = nil
}
